<div class="wrap">
    <?php include(YARPP_DIR.'/includes/phtmls/yarpp_settings_header.phtml') ?>

    <div id="yarpp_switch_container">
        <ul id="yarpp_switch_tabs">
            <li>
                <a href="options-general.php?page=yarpp&mode=basic">YARPP Basic</a>
            </li>
        </ul>

        <div class="yarpp_switch_content">
            <p>
                The settings bellow allow you to configure the Basic version of Yet Another Related Post Plugin (YARPP).
            </p>
        </div>
    </div>

    <form method="post">

        <div id="poststuff" class="metabox-holder has-right-sidebar">

            <?php if (!$yarpp->get_option('rss_display')): ?>
                <style>
                    .rss_displayed {
                        display: none;
                    }
                </style>
            <?php endif ?>

            <!-- Side column -->
            <div class="inner-sidebar" id="side-info-column">
                <?php do_meta_boxes('settings_page_yarpp', 'side', array()) ?>
            </div>

            <!-- Main Content -->

            <div id="post-body-content">
                <?php do_meta_boxes('settings_page_yarpp', 'normal', array()) ?>
            </div>

            <script>
                var spinner = '<?php echo esc_url(admin_url('images/spinner-2x.gif')) ?>',
                    loading = '<img height="20px" width="20px" class="loading" src="'+spinner+'" alt="loading..."/>';
            </script>

            <div>
                <input type="submit" class='button-primary' name="update_yarpp" value="<?php _e('Save Changes')?>" />
                <?php wp_nonce_field( 'update_yarpp', 'update_yarpp-nonce' ); ?>
            </div>

        </div><!--#poststuff-->

    </form>

</div>